### ISSUE TITLE
Devices window

### ISSUE THREAD

**Issue by Lemi0002** [linescaleGUI/linescaleGUI#20]
### Tracked by #2
A separate window in which the user can connect, disconnect, configure and view information about one device. The initial implementation should not prevent the multi-device extension tracked in #31.

```[tasklist]
### Tasks
- [x] #32
- [x] #33
- [x] #34
- [ ] https://github.com/linescaleGUI/linescaleGUI/issues/83
```

**Comment by ni-m** [comment]
Reopen to track the change of the unit from the UI.
